//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstUser
    {
        public int Id { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<int> OrgCode { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string Addr { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<short> ActivInd { get; set; }
        public Nullable<int> LevelInd { get; set; }
        public string CorpNameE { get; set; }
        public string CorpNameH { get; set; }
        public Nullable<int> ZoneCode { get; set; }
        public Nullable<int> WardCode { get; set; }
        public Nullable<int> GarageCode { get; set; }
        public byte[] IPPassword { get; set; }
        public Nullable<System.Guid> SaltKey { get; set; }
    }
}
